steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/kcg-helpme-2025/kcghelp', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/kcg-helpme-2025/kcghelp']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'kcghelp'
      - '--image'
      - 'gcr.io/kcg-helpme-2025/kcghelp'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'
timeout: '1200s'
