name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Docker Build
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT }}/kcg .

      - name: Push to Container Registry
        run: |
          docker push gcr.io/${{ secrets.GCP_PROJECT }}/kcg

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy kcg \
            --image gcr.io/${{ secrets.GCP_PROJECT }}/kcg \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated
