name: Deploy to Cloud Run

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: kcg-helpmE-2025
          install_components: 'beta'

      - name: Deploy to Cloud Run
        run: |
          gcloud builds submit --tag gcr.io/kcg-helpmE-2025/lifesaver-api
          gcloud run deploy lifesaver-api \
            --image gcr.io/kcg-helpmE-2025/lifesaver-api \
            --platform managed \
            --region us \
            --allow-unauthenticated
